### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by charliez0** [luolongfei/freenom#154]
**描述问题**

```
A clear and concise description of what the bug is.
```
在非root用户下会报错，但不影响续期

**重现步骤**
```bash
sudo -u www-data -g www-data php run
```

**截图&日志**
```
[2022-10-18 17:34:20] {"type":2,"message":"fopen(\/var\/www\/freenom\/logs\/2022-10\/18.log): Failed to open stream: Permission denied","file":"\/var\/www\/freenom\/app\/helpers.php","line":98}
PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/freenom/logs/2022-10/18.log" could not be opened in append mode: Failed to open stream: Permission denied in /var/www/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:110
Stack trace:
#0 /var/www/freenom/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write()
#1 /var/www/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle()
#2 /var/www/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(458): Monolog\Logger->addRecord()
#3 /var/www/freenom/libs/Log.php(117): Monolog\Logger->addError()
#4 /var/www/freenom/run(54): Luolongfei\Libs\Log::error()
#5 [internal function]: customize_error_handler()
#6 {main}
  thrown in /var/www/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 110

Fatal error: Uncaught UnexpectedValueException: The stream or file "/var/www/freenom/logs/2022-10/18.log" could not be opened in append mode: Failed to open stream: Permission denied in /var/www/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:110
Stack trace:
#0 /var/www/freenom/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write()
#1 /var/www/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle()
#2 /var/www/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(458): Monolog\Logger->addRecord()
#3 /var/www/freenom/libs/Log.php(117): Monolog\Logger->addError()
#4 /var/www/freenom/run(54): Luolongfei\Libs\Log::error()
#5 [internal function]: customize_error_handler()
#6 {main}
  thrown in /var/www/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 110
```
**你做了哪些尝试**

```
确认freenom目录以及子目录权限都为www-data:www-data
```

**环境信息**

- 系统：  *Ubuntu 22.04.1 LTS*
- PHP 版本：  *php8.1.2*
- 脚本版本：  *v0.5.1*
- 是否 Docker：  *No*

**额外的备注**

- Add any other context about the problem here.
- 可额外备注比如你的运行环境是否 NAS，是否宝塔面板等信息

**Comment by charliez0** [comment]
貌似是新建的目录权限不足的原因，新建的目录没有x权限

**Comment by luolongfei** [comment]
你拉取代码是不是用的 root 账户？

**Comment by luolongfei** [comment]
你看看 logs 目录的权限是怎样的，有没有读写权限

**Comment by charliez0** [comment]
![image](https://user-images.githubusercontent.com/20507989/196418617-d5a6e92b-563e-45d8-b549-85e5b2fc3003.png)
![image](https://user-images.githubusercontent.com/20507989/196418819-92a69163-e49e-426f-871a-cc2dab77967e.png)

**Comment by luolongfei** [comment]
`chmod -Rf 666 logs`
然后再试

**Comment by luolongfei** [comment]
你的 logs 目录其他群组和用户没有写入权限

**Comment by charliez0** [comment]
我本来就是在www-data用户下面设置的定时任务

**Comment by charliez0** [comment]
![image](https://user-images.githubusercontent.com/20507989/196423904-8b7f79a6-9826-4e31-8a60-776b50308d41.png)
是新建的目录默认权限不足引起的问题，这个问题只有在非root才有体现

**Comment by luolongfei** [comment]
为什么 logs/2022-10 目录的权限没有改到？

**Comment by charliez0** [comment]
我是先改的logs的权限再运行的程序，2022-10是程序自动创建的自己都进不去的目录

**Comment by charliez0** [comment]
如果创建后改了的话，下个月还会出现一样的问题，总不可能每个月都去碰一把吧

**Comment by luolongfei** [comment]
2022-10 是你修改权限后程序创建的？

**Comment by luolongfei** [comment]
先标记一下，等我空了看看

**Comment by charliez0** [comment]
是的，是程序自动创建的

**Comment by 1-1-2** [comment]
附议。

> 我是先改的logs的权限再运行的程序，2022-10是程序自动创建的自己都进不去的目录

程序创建的月份目录（如2023-03），权限是644，如果不+x程序自己都进不去
