### ISSUE TITLE
在 AC 跑，结果是可以了，但日志报错，导致 Action 那里显示是错误的。

### ISSUE THREAD

**Issue by fscarmen** [luolongfei/freenom#159]
**描述问题**

```
可以看到已经跑出来结果了，tg也收到相应的通知，但后续的写入日志报错。
```

**重现步骤**

```
######  说明  ######
# 1、Fork 本仓库
# 2、在你 Fork 的本仓库下的 Settings > Secrets 画面追加以下几个 secret 变量：
# FREENOM_USERNAME、FREENOM_PASSWORD、MULTIPLE_ACCOUNTS、MAIL_USERNAME、MAIL_PASSWORD、TO、MAIL_ENABLE、TELEGRAM_CHAT_ID、
# TELEGRAM_BOT_TOKEN、TELEGRAM_BOT_ENABLE、NOTICE_FREQ
# （注：此处列出了所有可用变量，你只用追加你需要用到的变量，变量的具体含义请参考本项目的 .env 文件中的说明，一般情况下，.env 文件中的某些
#  项存在默认值，如果默认值满足你的需求则可不追加到 Secrets，它们会保持默认）
#
# 下面定时任务中的时间是世界时间，每天 10:00 执行，由于创建虚拟环境会消耗时间，故任务会延迟 30 秒左右执行
#
# @Author of yml configuration file: RouRouX <https://github.com/RouRouX> & mybsdc <mybsdc@gmail.com>
#
######  end 说明  ######

name: Run it on action

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 20 20 * * 3
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: Run it on action
    steps:
      - name: Checkout master
        uses: actions/checkout@v3.1.0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      - name: Setting
        run: |
          echo 'Renew freenom domain name automatically.'
          echo '@Author of yml configuration file: RouRouX <https://github.com/RouRouX> & mybsdc <mybsdc@gmail.com>'
          echo '@Url: https://github.com/luolongfei/freenom'
          chmod -Rf +x logs
          cp .env.example .env
          if [[ ('${{ secrets.FREENOM_USERNAME }}' == '' || '${{ secrets.FREENOM_PASSWORD }}' == '') && '${{ secrets.MULTIPLE_ACCOUNTS }}' == '' ]]; then echo '你在 Github 的当前项目的 Settings > Secrets 画面没有设置任何与账户信息相关的 secret 值，无法正常运行，请添加新的 secret 值，设置 FREENOM_USERNAME 与 FREENOM_PASSWORD，或者设置 MULTIPLE_ACCOUNTS，以及 .env 文件中其它必要项，各项的具体含义与格式参考本项目 .env 文件中的说明。'; fi
          if [ '${{ secrets.FREENOM_USERNAME }}' != '' ]; then sed -i "s/^FREENOM_USERNAME=.*$/FREENOM_USERNAME='${{ secrets.FREENOM_USERNAME }}'/" .env; fi
          if [ '${{ secrets.FREENOM_PASSWORD }}' != '' ]; then sed -i "s/^FREENOM_PASSWORD=.*$/FREENOM_PASSWORD='${{ secrets.FREENOM_PASSWORD }}'/" .env; fi
          if [ '${{ secrets.MULTIPLE_ACCOUNTS }}' != '' ]; then sed -i "s/^MULTIPLE_ACCOUNTS=.*$/MULTIPLE_ACCOUNTS='${{ secrets.MULTIPLE_ACCOUNTS }}'/" .env; fi
          if [ '${{ secrets.MAIL_USERNAME }}' != '' ]; then sed -i "s/^MAIL_USERNAME=.*$/MAIL_USERNAME='${{ secrets.MAIL_USERNAME }}'/" .env; fi
          if [ '${{ secrets.MAIL_PASSWORD }}' != '' ]; then sed -i "s/^MAIL_PASSWORD=.*$/MAIL_PASSWORD='${{ secrets.MAIL_PASSWORD }}'/" .env; fi
          if [ '${{ secrets.TO }}' != '' ]; then sed -i "s/^TO=.*$/TO='${{ secrets.TO }}'/" .env; fi
          if [ '${{ secrets.MAIL_ENABLE }}' != '' ]; then sed -i "s/^MAIL_ENABLE=.*$/MAIL_ENABLE='${{ secrets.MAIL_ENABLE }}'/" .env; fi
          if [ '${{ secrets.TELEGRAM_CHAT_ID }}' != '' ]; then sed -i "s/^TELEGRAM_CHAT_ID=.*$/TELEGRAM_CHAT_ID='${{ secrets.TELEGRAM_CHAT_ID }}'/" .env; fi
          if [ '${{ secrets.TELEGRAM_BOT_TOKEN }}' != '' ]; then sed -i "s/^TELEGRAM_BOT_TOKEN=.*$/TELEGRAM_BOT_TOKEN='${{ secrets.TELEGRAM_BOT_TOKEN }}'/" .env; fi
          if [ '${{ secrets.TELEGRAM_BOT_ENABLE }}' != '' ]; then sed -i "s/^TELEGRAM_BOT_ENABLE=.*$/TELEGRAM_BOT_ENABLE='${{ secrets.TELEGRAM_BOT_ENABLE }}'/" .env; fi
          if [ '${{ secrets.NOTICE_FREQ }}' != '' ]; then sed -i "s/^NOTICE_FREQ=.*$/NOTICE_FREQ='${{ secrets.NOTICE_FREQ }}'/" .env; fi
          sed -i "s/^ON_GITHUB_ACTIONS=.*$/ON_GITHUB_ACTIONS=true/" .env
      - name: Setup WARP
        run: |
          sudo apt-get -y update
          sudo apt-get -y install --no-install-recommends net-tools iproute2 openresolv dnsutils iptables wireguard-tools
          echo "[Interface]
          PrivateKey = cKE7LmCF61IhqqABGhvJ44jWXp8fKymcMAEVAzbDF2k=
          Address = 172.16.0.2/32
          Address = fd01:5ca1:ab1e:823e:e094:eb1c:ff87:1fab/128
          DNS = 8.8.8.8,8.8.4.4
          MTU = 1280
          [Peer]
          PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
          AllowedIPs = 0.0.0.0/0
          AllowedIPs = ::/0
          Endpoint = 162.159.193.10:2408" | sudo tee /etc/wireguard/wgcf.conf
          sudo wg-quick up wgcf
          sudo curl -s4m8 https://ip.gs/json
      - name: Run
        run: |
          php run

```

**截图&日志**

![image](https://user-images.githubusercontent.com/62703343/198289361-8b470364-e52b-4fdc-a932-d9161a4dc900.png)

<img width="589" alt="image" src="https://user-images.githubusercontent.com/62703343/198290432-9ca0ebfb-8df8-4c4c-b3af-20c9b4f707dd.png">

**你做了哪些尝试**

```
无，希望老大看一下如何处理，不报错。
```

**环境信息**

Github Action
- 系统：  *（例如 debian11 x64）*
- PHP 版本：  *（例如 php8.0）*
- 脚本版本：  *（例如 v0.4.5）*
- 是否 Docker：  *（例如 是）*

**额外的备注**

- Add any other context about the problem here.
- 可额外备注比如你的运行环境是否 NAS，是否宝塔面板等信息

**Comment by luolongfei** [comment]
具体报的什么错？是不是权限相关

**Comment by fscarmen** [comment]
> 具体报的什么错？是不是权限相关

是的，在 Run php run 这步，在 yml 文件已经加入 `chmod -Rf +x logs`

```
php run
  shell: /usr/bin/bash -e {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: ***
[2022-***0-27 20:[3](https://github.com/cat2/freenom/actions/runs/3332371925/jobs/5523792802#step:6:3)8:***7] 当前程序版本 v0.5.*** 
[2022-***0-27 20:38:***7] 共发现 2 个 freenom 账户 
[2022-***0-27 20:38:***7] 开始处理第 *** 个 freenom 账户：a*******@gmail.com [***/2] 
[2022-***0-27 20:38:***9] a*******@gmail.com：执行成功，今次没有需要续期的域名。 
[2022-***0-27 20:38:***9] 开始处理第 2 个 freenom 账户： a*******@enayu.com [2/2] 
[2022-***0-27 20:38:20] a*******@enayu.com：执行成功，今次没有需要续期的域名。 
[2022-***0-27 20:38:20] {"type":2,"message":"fopen(\/home\/runner\/work\/freenom\/freenom\/logs\/2022-***0\/27.log): failed to open stream: Permission denied","file":"\/home\/runner\/work\/freenom\/freenom\/app\/helpers.php","line":98} 
PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/home/runner/work/freenom/freenom/logs/2022-***0/27.log" could not be opened in append mode: failed to open stream: Permission denied in /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:***0
Stack trace:
#0 /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)
#*** /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(3[4](https://github.com/cat2/freenom/actions/runs/3332371925/jobs/5523792802#step:6:4)4): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(4[5](https://github.com/cat2/freenom/actions/runs/3332371925/jobs/5523792802#step:6:5)8): Monolog\Logger->addRecord(400, '\xE7\xA8\x8B\xE5\xBA\x8F\xE[6](https://github.com/cat2/freenom/actions/runs/3332371925/jobs/5523792802#step:6:6)\x84\x8F\xE5\xA4\x96\xE[7](https://github.com/cat2/freenom/actions/runs/3332371925/jobs/5523792802#step:6:8)\xBB\x[8](https://github.com/cat2/freenom/actions/runs/3332371925/jobs/5523792802#step:6:9)8...', Array)
#3 /home/runner/work/freenom/freenom/libs/Log.php(***7): Monolog\Logger->addError('\xE7\xA8\x8B\xE5\xBA\x8F\xE6\x84\x8F\xE5\xA4\x[9](https://github.com/cat2/freenom/actions/runs/3332371925/jobs/5523792802#step:6:10)6\xE7\xBB\x88...', Array)
#4 /home/runner/work/freenom/freenom/run(54): Luolongfei\Libs\Log::e in /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line ***0

Fatal error: Uncaught UnexpectedValueException: The stream or file "/home/runner/work/freenom/freenom/logs/2022-***0/27.log" could not be opened in append mode: failed to open stream: Permission denied in /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:***0
Stack trace:
#0 /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\Handler\StreamHandler->write(Array)
#*** /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Logger.php(458): Monolog\Logger->addRecord(400, '\xE7\xA8\x8B\xE5\xBA\x8F\xE6\x84\x8F\xE5\xA4\x96\xE7\xBB\x88...', Array)
#3 /home/runner/work/freenom/freenom/libs/Log.php(***7): Monolog\Logger->addError('\xE7\xA8\x8B\xE5\xBA\x8F\xE6\x84\x8F\xE5\xA4\x96\xE7\xBB\x88...', Array)
#4 /home/runner/work/freenom/freenom/run(54): Luolongfei\Libs\Log::e in /home/runner/work/freenom/freenom/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line ***0
Error: Process completed with exit code [25](https://github.com/cat2/freenom/actions/runs/3332371925/jobs/5523792802#step:6:26)5.
```

**Comment by luolongfei** [comment]
加`chmod -Rf 777 logs`，`+x`是执行权限，日志目录要的是读写权限，把777换成666应该也行。

**Comment by fscarmen** [comment]
是权限的问题，经常详细测试，看错误的提示如下。我推测应该是在 logs 下应该有个以年-月为名的文件夹，下面有 日期.log 的文件用于记录日志的。报错为没有权限的，故我加了以下两条指令，创建文件夹，加权限。运行成功，没有报错了。

```
sudo mkdir -p logs/$(date +"%Y")-$(date +"%m")
sudo chmod -Rf 777 logs
```

![image](https://user-images.githubusercontent.com/62703343/198500114-51c4b7b5-ec63-45eb-8ce0-b10ce4524a7d.png)

全部 yml 文件如下，希望帮到有需要用ac的朋友，同时作者可以看看在脚本处稍作处理（现在相当于要另外加建目录的操作，不够一气呵成的感觉）。
```
######  说明  ######
# 1、Fork 本仓库
# 2、在你 Fork 的本仓库下的 Settings > Secrets 画面追加以下几个 secret 变量：
# FREENOM_USERNAME、FREENOM_PASSWORD、MULTIPLE_ACCOUNTS、MAIL_USERNAME、MAIL_PASSWORD、TO、MAIL_ENABLE、TELEGRAM_CHAT_ID、
# TELEGRAM_BOT_TOKEN、TELEGRAM_BOT_ENABLE、NOTICE_FREQ
# （注：此处列出了所有可用变量，你只用追加你需要用到的变量，变量的具体含义请参考本项目的 .env 文件中的说明，一般情况下，.env 文件中的某些
#  项存在默认值，如果默认值满足你的需求则可不追加到 Secrets，它们会保持默认）
#
# 下面定时任务中的时间是世界时间，每天 10:00 执行，由于创建虚拟环境会消耗时间，故任务会延迟 30 秒左右执行
#
# @Author of yml configuration file: RouRouX <https://github.com/RouRouX> & mybsdc <mybsdc@gmail.com>
#
######  end 说明  ######

name: Run it on action

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 20 20 * * 3
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: Run it on action
    steps:
      - name: Checkout master
        uses: actions/checkout@v3.1.0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      - name: Setting
        run: |
          echo 'Renew freenom domain name automatically.'
          echo '@Author of yml configuration file: RouRouX <https://github.com/RouRouX> & mybsdc <mybsdc@gmail.com>'
          echo '@Url: https://github.com/luolongfei/freenom'
          cp .env.example .env
          sudo mkdir -p logs/$(date +"%Y")-$(date +"%m")
          sudo chmod -Rf 777 logs
          if [[ ('${{ secrets.FREENOM_USERNAME }}' == '' || '${{ secrets.FREENOM_PASSWORD }}' == '') && '${{ secrets.MULTIPLE_ACCOUNTS }}' == '' ]]; then echo '你在 Github 的当前项目的 Settings > Secrets 画面没有设置任何与账户信息相关的 secret 值，无法正常运行，请添加新的 secret 值，设置 FREENOM_USERNAME 与 FREENOM_PASSWORD，或者设置 MULTIPLE_ACCOUNTS，以及 .env 文件中其它必要项，各项的具体含义与格式参考本项目 .env 文件中的说明。'; fi
          if [ '${{ secrets.FREENOM_USERNAME }}' != '' ]; then sed -i "s/^FREENOM_USERNAME=.*$/FREENOM_USERNAME='${{ secrets.FREENOM_USERNAME }}'/" .env; fi
          if [ '${{ secrets.FREENOM_PASSWORD }}' != '' ]; then sed -i "s/^FREENOM_PASSWORD=.*$/FREENOM_PASSWORD='${{ secrets.FREENOM_PASSWORD }}'/" .env; fi
          if [ '${{ secrets.MULTIPLE_ACCOUNTS }}' != '' ]; then sed -i "s/^MULTIPLE_ACCOUNTS=.*$/MULTIPLE_ACCOUNTS='${{ secrets.MULTIPLE_ACCOUNTS }}'/" .env; fi
          if [ '${{ secrets.MAIL_USERNAME }}' != '' ]; then sed -i "s/^MAIL_USERNAME=.*$/MAIL_USERNAME='${{ secrets.MAIL_USERNAME }}'/" .env; fi
          if [ '${{ secrets.MAIL_PASSWORD }}' != '' ]; then sed -i "s/^MAIL_PASSWORD=.*$/MAIL_PASSWORD='${{ secrets.MAIL_PASSWORD }}'/" .env; fi
          if [ '${{ secrets.TO }}' != '' ]; then sed -i "s/^TO=.*$/TO='${{ secrets.TO }}'/" .env; fi
          if [ '${{ secrets.MAIL_ENABLE }}' != '' ]; then sed -i "s/^MAIL_ENABLE=.*$/MAIL_ENABLE='${{ secrets.MAIL_ENABLE }}'/" .env; fi
          if [ '${{ secrets.TELEGRAM_CHAT_ID }}' != '' ]; then sed -i "s/^TELEGRAM_CHAT_ID=.*$/TELEGRAM_CHAT_ID='${{ secrets.TELEGRAM_CHAT_ID }}'/" .env; fi
          if [ '${{ secrets.TELEGRAM_BOT_TOKEN }}' != '' ]; then sed -i "s/^TELEGRAM_BOT_TOKEN=.*$/TELEGRAM_BOT_TOKEN='${{ secrets.TELEGRAM_BOT_TOKEN }}'/" .env; fi
          if [ '${{ secrets.TELEGRAM_BOT_ENABLE }}' != '' ]; then sed -i "s/^TELEGRAM_BOT_ENABLE=.*$/TELEGRAM_BOT_ENABLE='${{ secrets.TELEGRAM_BOT_ENABLE }}'/" .env; fi
          if [ '${{ secrets.NOTICE_FREQ }}' != '' ]; then sed -i "s/^NOTICE_FREQ=.*$/NOTICE_FREQ='${{ secrets.NOTICE_FREQ }}'/" .env; fi
          sed -i "s/^ON_GITHUB_ACTIONS=.*$/ON_GITHUB_ACTIONS=true/" .env
      - name: Setup WARP
        run: |
          sudo apt-get -y update
          sudo apt-get -y install --no-install-recommends openresolv wireguard-tools
          echo "[Interface]
          PrivateKey = cKE7LmCF61IhqqABGhvJ44jWXp8fKymcMAEVAzbDF2k=
          Address = 172.16.0.2/32
          Address = fd01:5ca1:ab1e:823e:e094:eb1c:ff87:1fab/128
          DNS = 8.8.8.8,8.8.4.4
          MTU = 1280
          [Peer]
          PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
          AllowedIPs = 0.0.0.0/0
          AllowedIPs = ::/0
          Endpoint = 162.159.193.10:2408" | sudo tee /etc/wireguard/wgcf.conf
          sudo wg-quick up wgcf
          sudo curl -s4m8 https://ip.gs/json
      - name: Run
        run: |
          php run
```

**Comment by BA7JCM** [comment]
我想问下，跑的时候在”setup warp“那里就卡住了，看日志显示”ip link add wgcf type wireguard “之后就一直卡在那里，是啥情况，卡十几二十分钟也不会进行下一步

**Comment by fscarmen** [comment]
> 我想问下，跑的时候在”setup warp“那里就卡住了，看日志显示”ip link add wgcf type wireguard “之后就一直卡在那里，是啥情况，卡十几二十分钟也不会进行下一步

那步有时候受github的环境，偶尔卡着，右上角的重新运行即可，我刚刚才试完，没有问题的。
